-- Demo typed content. German is canonical; some Ukrainian fields are left empty
-- on purpose so the German fallback (AC-6) has something to render.

INSERT INTO content_entries (typed_key, payload, published_payload, publication_state, published_version)
VALUES
  ('home',
   '{"hero":{"de":"Ukrainische Küche in Kassel","en":"Ukrainian kitchen in Kassel"},
     "storyTeaser":{"de":"Borschtsch, Wareniki, Pampuschky und mehr — handgemacht und herzlich.",
                    "en":"Borscht, varenyky, pampushky and more — handmade and heartfelt."}}',
   '{"hero":{"de":"Ukrainische Küche in Kassel","en":"Ukrainian kitchen in Kassel"},
     "storyTeaser":{"de":"Borschtsch, Wareniki, Pampuschky und mehr — handgemacht und herzlich.",
                    "en":"Borscht, varenyky, pampushky and more — handmade and heartfelt."}}',
   'published', 1),
  ('about',
   '{"intro":{"de":"Über uns","en":"About us","uk":"Про нас"},
     "story":{"de":"Kalyna ist ein fiktives Portfolio-Demonstrations-Restaurant. Die Rezepte orientieren sich an der ukrainischen Hausküche."}}',
   '{"intro":{"de":"Über uns","en":"About us","uk":"Про нас"},
     "story":{"de":"Kalyna ist ein fiktives Portfolio-Demonstrations-Restaurant. Die Rezepte orientieren sich an der ukrainischen Hausküche."}}',
   'published', 1),
  ('faq',
   '{"items":[
      {"question":{"de":"Bietet Kalyna auch vegetarische Gerichte an?"},
       "answer":{"de":"Ja, eine Auswahl veganer und vegetarischer Gerichte ist immer auf der Speisekarte."},
       "category":"restaurant"},
      {"question":{"de":"Kann ich ohne Konto bestellen?"},
       "answer":{"de":"Ja, Bestellung und Tischreservierung funktionieren vollständig ohne Konto."},
       "category":"order"}]}',
   '{"items":[
      {"question":{"de":"Bietet Kalyna auch vegetarische Gerichte an?"},
       "answer":{"de":"Ja, eine Auswahl veganer und vegetarischer Gerichte ist immer auf der Speisekarte."},
       "category":"restaurant"},
      {"question":{"de":"Kann ich ohne Konto bestellen?"},
       "answer":{"de":"Ja, Bestellung und Tischreservierung funktionieren vollständig ohne Konto."},
       "category":"order"}]}',
   'published', 1),
  ('lunch',
   '{"intro":{"de":"Unser Mittagstisch — täglich frisch zubereitet."},
     "validFrom":"2026-09-01","validUntil":"2026-12-31"}',
   '{"intro":{"de":"Unser Mittagstisch — täglich frisch zubereitet."},
     "validFrom":"2026-09-01","validUntil":"2026-12-31"}',
   'published', 1),
  ('events',
   '{"items":[
      {"title":{"de":"Ukrainischer Abend mit Live-Musik"},
       "summary":{"de":"Ein kulinarischer Abend mit ukrainischer Küche und Musik."},
       "startsAt":"2026-10-24","endsAt":"2026-10-24"},
      {"title":{"de":"Borschtsch-Workshop"},
       "summary":{"de":"Gemeinsam kochen wir Borschtsch nach Hausrezept."},
       "startsAt":"2026-11-07","endsAt":"2026-11-07"}]}',
   '{"items":[
      {"title":{"de":"Ukrainischer Abend mit Live-Musik"},
       "summary":{"de":"Ein kulinarischer Abend mit ukrainischer Küche und Musik."},
       "startsAt":"2026-10-24","endsAt":"2026-10-24"},
      {"title":{"de":"Borschtsch-Workshop"},
       "summary":{"de":"Gemeinsam kochen wir Borschtsch nach Hausrezept."},
       "startsAt":"2026-11-07","endsAt":"2026-11-07"}]}',
   'published', 1),
  ('gallery',
   '{"items":[
      {"storagePath":"/2borsch.jpg","alt":{"de":"Borschtsch mit Sauerrahm und Dill"}},
      {"storagePath":"/uzvar1.jpg","alt":{"de":"Uzvar aus getrockneten Früchten"}}]}',
   '{"items":[
      {"storagePath":"/2borsch.jpg","alt":{"de":"Borschtsch mit Sauerrahm und Dill"}},
      {"storagePath":"/uzvar1.jpg","alt":{"de":"Uzvar aus getrockneten Früchten"}}]}',
   'published', 1),
  ('catering',
   '{"intro":{"de":"Feiern und Veranstaltungen ab 10 Gästen."},
     "constraints":{"de":"Wir liefern auf Anfrage innerhalb von Kassel und Umgebung."},
     "responseNote":{"de":"Unverbindliche Anfrage — Sie erhalten eine Antwort innerhalb von zwei Werktagen."}}',
   '{"intro":{"de":"Feiern und Veranstaltungen ab 10 Gästen."},
     "constraints":{"de":"Wir liefern auf Anfrage innerhalb von Kassel und Umgebung."},
     "responseNote":{"de":"Unverbindliche Anfrage — Sie erhalten eine Antwort innerhalb von zwei Werktagen."}}',
   'published', 1);