import type { PublicMenu, PublicMenuItem } from "./domain";

function demoItem(
  item: Omit<
    PublicMenuItem,
    "allergens" | "additives" | "modifierGroups" | "searchText"
  > & {
    allergens?: PublicMenuItem["allergens"];
  },
): PublicMenuItem {
  return {
    ...item,
    allergens: item.allergens ?? [],
    additives: [],
    modifierGroups: [],
    searchText: `${item.name} ${item.description}`.toLowerCase(),
  };
}

const ITEMS: PublicMenuItem[] = [
  demoItem({
    id: "30000000-0000-0000-0000-000000000001",
    slug: "borschtsch",
    categoryId: "10000000-0000-0000-0000-000000000001",
    categorySlug: "suppen",
    categoryName: "Suppen",
    name: "Borschtsch",
    description:
      "Ukrainische Rote-Bete-Suppe mit Fleisch, Sauerrahm und frischem Dill.",
    portionLabel: "Portion · 450 ml",
    basePriceCents: 790,
    glutenFree: false,
    vegan: false,
    vegetarian: false,
    spicy: false,
    popular: true,
    image: {
      storagePath: "/2borsch.jpg",
      alt: "Borschtsch mit Sauerrahm und Dill",
    },
    sortOrder: 1,
    categorySortOrder: 1,
    allergens: [
      { code: "milk", label: "Milch", containment: "contains" },
      { code: "celery", label: "Sellerie", containment: "contains" },
    ],
  }),
  demoItem({
    id: "30000000-0000-0000-0000-000000000002",
    slug: "vegetarischer-borschtsch",
    categoryId: "10000000-0000-0000-0000-000000000001",
    categorySlug: "suppen",
    categoryName: "Suppen",
    name: "Vegetarischer Borschtsch",
    description: "Rote-Bete-Suppe ohne Fleisch, mit Sauerrahm.",
    portionLabel: "Portion · 450 ml",
    basePriceCents: 690,
    glutenFree: false,
    vegan: false,
    vegetarian: true,
    spicy: false,
    popular: true,
    image: {
      storagePath: "/1borsch.jpg",
      alt: "Vegetarischer Borschtsch mit Sauerrahm",
    },
    sortOrder: 2,
    categorySortOrder: 1,
    allergens: [
      { code: "milk", label: "Milch", containment: "contains" },
      { code: "celery", label: "Sellerie", containment: "contains" },
    ],
  }),
  demoItem({
    id: "30000000-0000-0000-0000-000000000003",
    slug: "wareniki-kartoffeln",
    categoryId: "10000000-0000-0000-0000-000000000002",
    categorySlug: "hauptgerichte",
    categoryName: "Hauptgerichte",
    name: "Wareniki mit Kartoffeln",
    description:
      "Ukrainische Teigtaschen mit Kartoffelfüllung und Röstzwiebeln.",
    portionLabel: "Portion · 8 Stück",
    basePriceCents: 990,
    glutenFree: false,
    vegan: false,
    vegetarian: true,
    spicy: false,
    popular: true,
    image: { storagePath: "/vareniki1.jpg", alt: "Wareniki mit Kartoffeln" },
    sortOrder: 1,
    categorySortOrder: 2,
    allergens: [
      { code: "gluten", label: "Gluten", containment: "contains" },
      { code: "eggs", label: "Eier", containment: "contains" },
      { code: "milk", label: "Milch", containment: "contains" },
    ],
  }),
  demoItem({
    id: "30000000-0000-0000-0000-000000000004",
    slug: "wareniki-kirschen",
    categoryId: "10000000-0000-0000-0000-000000000004",
    categorySlug: "desserts",
    categoryName: "Desserts",
    name: "Wareniki mit Kirschen",
    description:
      "Süße Teigtaschen mit Kirschfüllung und Sauerrahm.",
    portionLabel: "Portion · 8 Stück",
    basePriceCents: 890,
    glutenFree: false,
    vegan: false,
    vegetarian: true,
    spicy: false,
    popular: false,
    image: {
      storagePath: "/vareniki3.jpg",
      alt: "Wareniki mit Kirschen und Sauerrahm",
    },
    sortOrder: 1,
    categorySortOrder: 4,
    allergens: [
      { code: "gluten", label: "Gluten", containment: "contains" },
      { code: "eggs", label: "Eier", containment: "contains" },
      { code: "milk", label: "Milch", containment: "contains" },
    ],
  }),
  demoItem({
    id: "30000000-0000-0000-0000-000000000005",
    slug: "deruny",
    categoryId: "10000000-0000-0000-0000-000000000002",
    categorySlug: "hauptgerichte",
    categoryName: "Hauptgerichte",
    name: "Deruny",
    description: "Kartoffelpuffer mit Sauerrahm und frischem Dill.",
    portionLabel: "Portion · 4 Stück",
    basePriceCents: 850,
    glutenFree: false,
    vegan: false,
    vegetarian: true,
    spicy: false,
    popular: true,
    image: { storagePath: "/deruni1.jpg", alt: "Deruny mit Sauerrahm" },
    sortOrder: 2,
    categorySortOrder: 2,
    allergens: [
      { code: "gluten", label: "Gluten", containment: "contains" },
      { code: "eggs", label: "Eier", containment: "contains" },
      { code: "milk", label: "Milch", containment: "contains" },
    ],
  }),
  demoItem({
    id: "30000000-0000-0000-0000-000000000006",
    slug: "kiewer-kotelett",
    categoryId: "10000000-0000-0000-0000-000000000002",
    categorySlug: "hauptgerichte",
    categoryName: "Hauptgerichte",
    name: "Kiewer Kotelett",
    description:
      "Hähnchenkotelett mit Kräuterbutter, paniert und goldbraun gebraten.",
    portionLabel: "Portion · 2 Stück",
    basePriceCents: 1390,
    glutenFree: false,
    vegan: false,
    vegetarian: false,
    spicy: false,
    popular: true,
    image: {
      storagePath: "/kotleta_po_Kievski1.jpg",
      alt: "Paniertes Kiewer Kotelett",
    },
    sortOrder: 3,
    categorySortOrder: 2,
    allergens: [
      { code: "gluten", label: "Gluten", containment: "contains" },
      { code: "eggs", label: "Eier", containment: "contains" },
      { code: "milk", label: "Milch", containment: "contains" },
    ],
  }),
  demoItem({
    id: "30000000-0000-0000-0000-000000000008",
    slug: "holubzi",
    categoryId: "10000000-0000-0000-0000-000000000002",
    categorySlug: "hauptgerichte",
    categoryName: "Hauptgerichte",
    name: "Holubzi",
    description: "Kohlrouladen mit Reis und Hackfleisch in Tomatensauce.",
    portionLabel: "Portion · 3 Stück",
    basePriceCents: 1190,
    glutenFree: false,
    vegan: false,
    vegetarian: false,
    spicy: false,
    popular: false,
    image: { storagePath: "/golubtsi1.jpg", alt: "Holubzi in Tomatensauce" },
    sortOrder: 5,
    categorySortOrder: 2,
    allergens: [{ code: "celery", label: "Sellerie", containment: "contains" }],
  }),
  demoItem({
    id: "30000000-0000-0000-0000-000000000009",
    slug: "syrnyky",
    categoryId: "10000000-0000-0000-0000-000000000004",
    categorySlug: "desserts",
    categoryName: "Desserts",
    name: "Syrnyky",
    description:
      "Quarkpfannkuchen mit Sauerrahm oder hausgemachter Marmelade.",
    portionLabel: "Portion · 4 Stück",
    basePriceCents: 690,
    glutenFree: false,
    vegan: false,
    vegetarian: true,
    spicy: false,
    popular: true,
    image: { storagePath: "/vareniki2.jpg", alt: "Syrnyky mit Sauerrahm" },
    sortOrder: 2,
    categorySortOrder: 4,
    allergens: [
      { code: "gluten", label: "Gluten", containment: "contains" },
      { code: "eggs", label: "Eier", containment: "contains" },
      { code: "milk", label: "Milch", containment: "contains" },
    ],
  }),
  demoItem({
    id: "30000000-0000-0000-0000-00000000000b",
    slug: "uzvar",
    categoryId: "10000000-0000-0000-0000-000000000005",
    categorySlug: "getraenke",
    categoryName: "Getränke",
    name: "Uzvar",
    description: "Ukrainisches Kompott aus getrockneten Früchten.",
    portionLabel: "Portion · 0,33 l",
    basePriceCents: 350,
    glutenFree: true,
    vegan: true,
    vegetarian: true,
    spicy: false,
    popular: false,
    image: {
      storagePath: "/uzvar1.jpg",
      alt: "Uzvar aus getrockneten Früchten",
    },
    sortOrder: 1,
    categorySortOrder: 5,
  }),
];

export function getDemoPublicMenu(): PublicMenu {
  return {
    items: ITEMS,
    allergenReference: [
      { code: "gluten", label: "Gluten" },
      { code: "eggs", label: "Eier" },
      { code: "milk", label: "Milch" },
      { code: "celery", label: "Sellerie" },
    ],
    additiveReference: [],
  };
}

export function withDemoMenuFallback(menu: PublicMenu): PublicMenu {
  return menu.items.length > 0 ? menu : getDemoPublicMenu();
}